name: Terraform Validate

on:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform.yml"
  push:
    branches: [main]
    paths:
      - "terraform/**"

jobs:
  fmt-and-validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: terraform fmt (check only)
        run: terraform fmt -check -recursive

      - name: terraform init (no backend, validate only)
        run: terraform init -backend=false

      - name: terraform validate
        run: terraform validate

      - name: tflint
        uses: terraform-linters/setup-tflint@v4
      - run: tflint --init
      - run: tflint --recursive

      - name: checkov security scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform
          quiet: true
          skip_check: CKV_AWS_144

  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install linters
        run: pip install flake8
      - name: Lint Lambda source
        run: flake8 lambda/ingest lambda/query --max-line-length=110
